### ISSUE TITLE
No license text

### ISSUE THREAD

**Issue by skyrising** [ModCoderPack/MCInjector#6] opened 2018-12-04 22:42 UTC
A LICENSE file exists but is empty.

**Comment by Maniues** [comment] 2021-04-03 14:21
I know this is quite an old question, you probably already found a solution or just skipped it. I can see you have gone in the right direction (inferences from your repositories). For others who come here, I will help to clarify this problem a little.

My statement:
-------------
Problem
-------------
MC Forge and MCP do not have a clear license and unfortunately they limit their use quite strongly.
-----------
History
-----------
MCP or Mod Coder Pack was the first Minecraft modding tool. In short - the MC is made in Java, which is easy to decompile (convert it into human readable code). Companies that defend their code intentionally obfuscate it - change all names to those that are difficult to decipher (e.g. from the name: SpawnMob.class to ab.class). The MCP was deciphering these names. The MCP was initially distributed under the MCP license. It was a fairly restrictive license. Today, the MCP does not really exist. MCP has been merged with Forg for newer mc versions (above 1.12). Reason? The MCP allowed ONLY the modification of the MC code. Forge allows multiple mods at the same time. MCP was abandoned in favor of a better alternative.
------------
License:
------------
Forge is currently licensed under the LGPL license. However, there is a caution regarding the MCP data. The LGPL was not chosen by chance. If this were the GPL, the MCP data SHOULD be available under the GPL. The LGPL keeps it a secret. (THIS IS MY OPINION).
I have tried to contact the makers of MCP and Forge several times. Unfortunately, after a year / two, none of this. I asked why such a license, why not just license the Ford and MCP - for LGPL, GPL, MIT, Apache or some other license. No answer.

-------------
Solution
-------------
If you don't want to be constrained by a forge, there is an alternative. The alternative is quite good. It's called FabricMC. Since Forge uses some elements from mojang, hides the data, and closes the source, an alternative has been created. FabricMC adds its API, its ModLoader and its own mappings (instructions for deciphering variable and class names in MC code.)
More information: https://fabricmc.net/
Philosophy: https://fabricmc.net/wiki/faq:expert#philosophy
---------
NOTE
---------
THIS POST IS NOT SPONSORED BY FABRICMC. I JUST CHOOSE THIS IS A GOOD ALTERNATIVE.
--- If you want to forward, share or distribute this statement, you can do so in any way and for any purpose, just keep it in its original form (from the "Problem" section to my signature). Alternatively, you can remove any links attached to this post. ---
- Maniues -

**Comment by GalaxyLinus** [comment] 2021-04-03 15:29
why did I get notified for this via email? I've never done anything with this repositorie...

**Comment by jamierocks** [comment] 2021-04-03 16:24
> MC Forge and MCP do not have a clear license and unfortunately they limit their use quite strongly.

1. Minecraft Forge: LGPLv2.1 https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/LICENSE.txt
2. MCPConfig: modified zlib https://github.com/MinecraftForge/MCPConfig/blob/master/LICENSE

Though to the actual point of this issue, which you seem to have missed entirely, it would be nice is MCInjector had a license text.

> Forge is currently licensed under the LGPL license. However, there is a caution regarding the MCP data.

That may or may not still be relevant since the MCP data has a clearly defined license now.

> The LGPL was not chosen by chance. If this were the GPL, the MCP data SHOULD be available under the GPL.

(I'm not a solicitor, this is just my understanding of the situation)
The GPL would also be problematic with a Minecraft dependency (see the Bukkit/Craftbukkit scenario)... In any case there is nothing wrong with the LGPL, its a popular license within the community.

You seem to forget that MCP wasn't/isn't Forge's to license as they please anyhow.

> The LGPL keeps it a secret.

The data has never been a secret, and even with the old license it was possible to obtain permission to re-distribute as many did.

> I asked why such a license, why not just license the Ford and MCP - for LGPL, GPL, MIT, Apache or some other license. No answer.

I assume by Ford you mean Forge in which case both myself and you have established that it's LGPL. So far as MCPConfig goes, again modified zlib license.

> No answer.

MCPConfig was made available under a modified zlib license.

> Since Forge uses some elements from mojang

Minecraft? I'm not sure what elements you could be referring too that aren't common between Forge and Fabric.

> hides the data

What data? MCPBot exports daily, MCPConfig is available on both GitHub and MInecraft Forge's Maven. The existence of the data is well-known, if it is hiding - it's doing so in plain sight.

> and closes the source

I'm unaware of any part of Minecraft Forge, or its de-obfuscation pipeline that isn't visible-source at the very least (MCInjector being an example there).

> Philosophy: https://fabricmc.net/wiki/faq:expert#philosophy

I looked at this document, and I will be bringing this up with modmuss as something that needs updating or removal - its terribly out-of-date.

**Comment by LexManos** [comment] 2021-04-03 16:57
The issue is that I do not speak for Feshor/Searge. I can not place a license on the parts of their code in this project.
So this is the best you're gunna get. However as with most things I publish, my contributions are free to use. As well as the fact that future MC versions will be moving an alternative that does have it's license clearly defined.

**Closed as completed by LexManos** 2021-04-03 16:57 UTC
